image: openjdk:8-jdk-slim

stages:
  - test
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_OPTIONS: --no-daemon --info --stacktrace --warning-mode=all

.tests:
  stage: test
  script: ./de.prob2.kernel/gradlew ${GRADLE_OPTIONS} -b de.prob2.kernel/build.gradle clean check jacocoTestReport
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  artifacts:
    paths:
      - "*/build/jacoco"
      - "*/build/jacocoHtml"
      - "*/build/reports"
      - "*/build/test-results"
      - "**/prob_log.txt"
      - "**/ProB.log.*.log"
    when: always

.docker-tests:
  extends: .tests
  variables:
    DEBIAN_FRONTEND: noninteractive
    LANG: en_US.UTF-8
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - apt-get update &&  apt-get install -y git locales
    - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen 
    - dpkg-reconfigure --frontend=noninteractive locales
    - update-locale LANG=en_US.UTF-8


tests:jdk-8:
  extends: .docker-tests

tests:jdk-11:
  extends: .docker-tests
  image: openjdk:11-jdk-slim

tests:jdk-17:
  extends: .docker-tests
  image: openjdk:17-jdk-slim

tests:macos:
  extends: .tests
  tags:
    - macos

tests:windows64:
  extends: .tests
  before_script: []
  script: de.prob2.kernel\gradlew.bat %GRADLE_OPTIONS% -b de.prob2.kernel\build.gradle clean check jacocoTestReport
  tags:
    - prob
    - win64

publish:
  stage: deploy
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - apt-get update && apt-get install -y git 

    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in secring.gpg.enc       -out secring.gpg 
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in pubring.gpg.enc       -out pubring.gpg
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in gradle.properties.enc -out de.prob2.kernel/gradle.properties
  script:
    - ./de.prob2.kernel/gradlew ${GRADLE_OPTIONS} -b de.prob2.kernel/build.gradle publish
  only: 
    - master@stups/prob/prob2_kernel
    - develop@stups/prob/prob2_kernel
