image: eclipse-temurin:8

stages:
  - test
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

variables:
  GRADLE_OPTIONS: --no-daemon --info --stacktrace --warning-mode=all
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

.tests:
  stage: test
  script: ./gradlew ${GRADLE_OPTIONS} check jacocoTestReport
  artifacts:
    paths:
      - "*/build/jacoco"
      - "*/build/jacocoHtml"
      - "*/build/reports"
      - "*/build/test-results"
      - "**/prob_log.txt"
      - "**/ProB.log.*.log"
    reports:
      junit:
        - "*/build/test-results/**/TEST-*.xml"
    when: always

.docker-tests:
  extends: .tests
  variables:
    DEBIAN_FRONTEND: noninteractive
    LANG: en_US.UTF-8
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - apt-get update &&  apt-get install -y git locales
    - sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen 
    - dpkg-reconfigure --frontend=noninteractive locales
    - update-locale LANG=en_US.UTF-8


tests:jdk-8:
  extends: .docker-tests

tests:jdk-11:
  extends: .docker-tests
  image: eclipse-temurin:11

tests:jdk-17:
  extends: .docker-tests
  image: eclipse-temurin:17

tests:jdk-21:
  extends: .docker-tests
  image: eclipse-temurin:21

tests:macos:
  extends: .tests
  tags:
    - macos

tests:windows64:
  extends: .tests
  before_script: []
  script: cmd /c ".\gradlew.bat %GRADLE_OPTIONS% check jacocoTestReport"
  tags:
    - windows

publish:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y git 

    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in secring.gpg.enc       -out secring.gpg 
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in pubring.gpg.enc       -out pubring.gpg
    - openssl aes-256-cbc -pass "env:ENCRYPTION_PASSWORD" -d -a -md md5 -in gradle.properties.enc -out gradle.properties
  script:
    - ./gradlew ${GRADLE_OPTIONS} publish
  only: 
    - master@stups/prob/prob2_kernel
    - develop@stups/prob/prob2_kernel
