image: eclipse-temurin:8

stages:
  - test
  - deploy

cache:
  paths:
    - .gradle/caches
    - .gradle/notifications
    - .gradle/wrapper

variables:
  GRADLE_OPTIONS: --no-daemon --info --stacktrace --warning-mode=all
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

.tests:
  stage: test
  script: ./gradlew ${GRADLE_OPTIONS} check jacocoTestReport
  artifacts:
    paths:
      - "*/build/jacoco"
      - "*/build/jacocoHtml"
      - "*/build/reports"
      - "*/build/test-results"
      - "**/prob_log.txt"
      - "**/ProB.log.*.log"
    reports:
      junit:
        - "*/build/test-results/**/TEST-*.xml"
    when: always

.docker-tests:
  extends: .tests
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update && apt-get install -y git

tests:jdk-8:
  extends: .docker-tests

tests:jdk-11:
  extends: .docker-tests
  image: eclipse-temurin:11

tests:jdk-17:
  extends: .docker-tests
  image: eclipse-temurin:17

tests:jdk-21:
  extends: .docker-tests
  image: eclipse-temurin:21

tests:macos:
  extends: .tests
  tags:
    - macos

tests:windows64:
  extends: .tests
  before_script: []
  script: cmd /c ".\gradlew.bat %GRADLE_OPTIONS% check jacocoTestReport"
  tags:
    - windows

publish:
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y git 
  script:
    - openssl aes-256-cbc -d -base64 -pbkdf2 -pass "env:ENCRYPTION_PASSWORD" -in gradle.properties.enc -out gradle.properties
    - openssl aes-256-cbc -d -base64 -pbkdf2 -pass "env:ENCRYPTION_PASSWORD" -in pubring.gpg.enc -out pubring.gpg
    - openssl aes-256-cbc -d -base64 -pbkdf2 -pass "env:ENCRYPTION_PASSWORD" -in secring.gpg.enc -out secring.gpg
    - ./gradlew ${GRADLE_OPTIONS} publish
  only: 
    - master@stups/prob/prob2_kernel
    - develop@stups/prob/prob2_kernel
