stages:
  - test
  - deploy

cache:
  paths:
    - .gradle/caches
    - .gradle/notifications
    - .gradle/wrapper

variables:
  GRADLE_OPTIONS: --no-daemon --info --stacktrace --warning-mode=all
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

# For testing with older Java versions.
# Gradle 9 requires at least Java 17 to run,
# but can still compile/test using older JDKs if requested via a toolchain configuration.
# Thus, if the Java version provided by the eclipse-temurin image in question is too old to run Gradle,
# we additionally install Ubuntu's default JRE,
# which should always be new enough to run current Gradle versions.
# For example, as of 2025-11,
# the eclipse-temurin:8 image is based on Ubuntu 24.04 LTS (noble),
# whose default Java version is Java 21.
# Jobs that extend this template must also set the environment variable ORG_GRADLE_PROJECT_javaToolchainVersion
# to the Java version number of the eclipse-temurin image.
.linux_old_java:
  variables:
    # Change JAVA_HOME to the system default Java
    # so that Gradle runs using this newer Java version.
    JAVA_HOME: "/usr/lib/jvm/default-java"
  before_script:
    - apt-get update
    - apt-get install -y default-jre-headless

.tests:
  stage: test
  script: ./gradlew ${GRADLE_OPTIONS} check jacocoTestReport
  artifacts:
    paths:
      - "*/build/jacoco"
      - "*/build/jacocoHtml"
      - "*/build/reports"
      - "*/build/test-results"
      - "**/prob_log.txt"
      - "**/ProB.log.*.log"
    reports:
      junit:
        - "*/build/test-results/**/TEST-*.xml"
    when: always

.docker-tests:
  extends: .tests
  variables:
    DEBIAN_FRONTEND: noninteractive
  before_script:
    - apt-get update && apt-get install -y git

tests:jdk-8:
  extends:
    - .docker-tests
    - .linux_old_java
  image: eclipse-temurin:8
  variables:
    ORG_GRADLE_PROJECT_javaToolchainVersion: "8"

tests:jdk-11:
  extends:
    - .docker-tests
    - .linux_old_java
  image: eclipse-temurin:11
  variables:
    ORG_GRADLE_PROJECT_javaToolchainVersion: "11"

tests:jdk-17:
  extends: .docker-tests
  image: eclipse-temurin:17

tests:jdk-21:
  extends: .docker-tests
  image: eclipse-temurin:21

tests:macos:
  extends: .tests
  tags:
    - macos

tests:windows64:
  extends: .tests
  before_script: []
  script: cmd /c ".\gradlew.bat %GRADLE_OPTIONS% check jacocoTestReport"
  tags:
    - windows

publish:
  extends: .linux_old_java
  stage: deploy
  image: eclipse-temurin:8
  variables:
    ORG_GRADLE_PROJECT_javaToolchainVersion: "8"
  before_script:
    - apt-get update && apt-get install -y git 
  script:
    - openssl aes-256-cbc -d -base64 -pbkdf2 -pass "env:ENCRYPTION_PASSWORD" -in gradle.properties.enc -out gradle.properties
    - openssl aes-256-cbc -d -base64 -pbkdf2 -pass "env:ENCRYPTION_PASSWORD" -in pubring.gpg.enc -out pubring.gpg
    - openssl aes-256-cbc -d -base64 -pbkdf2 -pass "env:ENCRYPTION_PASSWORD" -in secring.gpg.enc -out secring.gpg
    - ./gradlew ${GRADLE_OPTIONS} publish closeStagingRepositories
  only: 
    - master@stups/prob/prob2_kernel
    - develop@stups/prob/prob2_kernel
