plugins {
	id("de.undercouch.download").version("5.7.0")
	
	id("jacoco")
	id("java-library")
}

// When making a release, please check that parserVersion matches what the specified version of probcli expects, to avoid unpredictable/inconsistent behavior!
def parserVersion = "2.16.0"
def probcliVersion = "1.16.1-nightly"
def cliDownloadURL
if (probcliVersion.endsWith("-nightly")) {
	if (!isSnapshot) {
		throw new GradleException("A release version of the ProB Java API cannot use a nightly version of probcli! Please change the variable probcliVersion (currently ${probcliVersion}) to a release version!")
	}
	cliDownloadURL = "https://stups.hhu-hosting.de/downloads/prob/cli/nightly"
} else {
	cliDownloadURL = "https://stups.hhu-hosting.de/downloads/prob/cli/releases/${probcliVersion}"
}

dependencies {
	// ProB parser dependencies (Eclipse Public License 1.0)
	api("de.hhu.stups:answerparser:${parserVersion}")
	api("de.hhu.stups:bparser:${parserVersion}")
	api("de.hhu.stups:ltlparser:${parserVersion}")
	api("de.hhu.stups:parserbase:${parserVersion}")
	api("de.hhu.stups:prologlib:${parserVersion}")
	api("de.hhu.stups:unicode:${parserVersion}")
	api("de.hhu.stups:theorymapping:${parserVersion}")

	// Other STUPS dependencies
	implementation("de.hhu.stups:alloy2b:2.0.0") // Eclipse Public License 1.0
	api("de.hhu.stups:ltl-dsl:0.2.2") // Eclipse Public License 1.0
	api("de.hhu.stups:rodin-eventb-ast:3.8.0") // Eclipse Public License 1.0
	implementation("de.hhu.stups:tla2bAST:1.4.2") // Eclipse Public License 1.0
	api("de.hhu.stups:tlc4b:1.2.3") // MIT License
	api("de.hhu.stups:value-translator:0.2.2") // MIT License

	// Logging
	api("org.slf4j:slf4j-api:2.0.18") // MIT License

	// Misc dependencies
	implementation("com.github.krukow:clj-ds:0.0.4") // Eclipse Public License 1.0
	implementation("com.google.guava:guava:33.6.0-jre") // Apache License 2.0
	api("com.google.inject:guice:7.0.0") // Apache License 2.0

	api(platform("com.fasterxml.jackson:jackson-bom:2.22.1"))
	api("com.fasterxml.jackson.core:jackson-databind")
	api("com.fasterxml.jackson.module:jackson-module-parameter-names")
	api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
	api("com.fasterxml.jackson.datatype:jackson-datatype-jdk8")
	implementation("org.apache.velocity:velocity-engine-core:2.4.1")

	// Test dependencies
	testImplementation("ch.qos.logback:logback-classic:1.6.1") // Eclipse Public License 1.0
	testImplementation(platform("org.junit:junit-bom:5.14.4"))
	testImplementation("org.junit.jupiter:junit-jupiter")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

final generatedResourcesDir = layout.buildDirectory.dir("generated-src/main/resources").get().asFile

sourceSets {
	main {
		resources {
			srcDir(generatedResourcesDir)
		}
	}
}

final platforms = [
	"macos",
	"linux64",
	"windows64",
]

task downloadBinaries(type: Download) {
	src(platforms.collect {platform -> "${cliDownloadURL}/probcli_${platform}.zip"})
	dest(new File(generatedResourcesDir, "de/prob/cli/binaries"))
	onlyIfModified(true)
}

def readCurrentGitCommit() {
	def proc = ["git", "rev-parse", "HEAD"].execute(null, rootProject.projectDir)
	def exitCode = proc.waitFor()
	if (exitCode != 0) {
		throw new IllegalStateException("git rev-parse command exited with status code ${exitCode}:\n" + proc.err.readLines().join("\n"))
	}
	return proc.in.readLines()[0]
}

processResources {
	inputs.property("version", project.version)
	inputs.property("currentGitCommit", readCurrentGitCommit())

	filesMatching("de/prob/build.properties") {
		expand(version: inputs.properties["version"], git: inputs.properties["currentGitCommit"])
	}
}

if (!rootProject.hasProperty("probHome")) {
	// Automatically download probcli/cspmf, unless a custom PROB_HOME is set
	processResources.dependsOn(downloadBinaries)
}

sourcesJar {
	// The downloaded binaries shouldn't go into the sources jar.
	exclude("de/prob/cli/binaries")
}

test {
	useJUnitPlatform()
	systemProperty("logback.configurationFile", "de/prob/logging/production.xml")
	testLogging {
		exceptionFormat = 'full'
	}
}

jacocoTestReport {
	reports {
		xml.required = false
		csv.required = false
		html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
	}
}

publishing.publications.mavenJava.pom.description = "Core of the ProB Java API"
